In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
import seaborn as sns

In [ ]:
df = pd.read_excel("/content/sample_data/AAPL.xlsx")
df

,Date,Open,High,Low,Close,Adj Close,Volume
0,2014-09-29,100.589996,100.690002,98.040001,99.620003,93.514290,142718700
1,2014-10-06,99.949997,102.379997,98.309998,100.730003,94.556244,280258200
2,2014-10-13,101.330002,101.779999,95.180000,97.669998,91.683792,358539800
3,2014-10-20,98.320000,105.489998,98.220001,105.220001,98.771042,358532900
4,2014-10-27,104.849998,108.040001,104.699997,108.000000,101.380676,220230600
...,...,...,...,...,...,...,...
179,2018-03-05,175.210007,180.000000,174.270004,179.979996,179.979996,139852700
180,2018-03-12,180.289993,183.500000,177.619995,178.020004,178.020004,155417500
181,2018-03-19,177.320007,177.470001,164.940002,164.940002,164.940002,172670700
182,2018-03-26,168.070007,175.149994,165.190002,167.779999,167.779999,157898400
183,2018-03-29,167.804993,171.750000,166.899994,167.779999,167.779999,38398505

In [ ]:
print(df.head())

        Date        Open        High         Low       Close   Adj Close  \
0 2014-09-29  100.589996  100.690002   98.040001   99.620003   93.514290
1 2014-10-06   99.949997  102.379997   98.309998  100.730003   94.556244
2 2014-10-13  101.330002  101.779999   95.180000   97.669998   91.683792
3 2014-10-20   98.320000  105.489998   98.220001  105.220001   98.771042
4 2014-10-27  104.849998  108.040001  104.699997  108.000000  101.380676

      Volume
0  142718700
1  280258200
2  358539800
3  358532900
4  220230600

In [ ]:
print(df.tail())

          Date        Open        High         Low       Close   Adj Close  \
179 2018-03-05  175.210007  180.000000  174.270004  179.979996  179.979996
180 2018-03-12  180.289993  183.500000  177.619995  178.020004  178.020004
181 2018-03-19  177.320007  177.470001  164.940002  164.940002  164.940002
182 2018-03-26  168.070007  175.149994  165.190002  167.779999  167.779999
183 2018-03-29  167.804993  171.750000  166.899994  167.779999  167.779999

        Volume
179  139852700
180  155417500
181  172670700
182  157898400
183   38398505

In [ ]:
print(df.shape)

(184, 7)

In [ ]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 184 entries, 0 to 183
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Date       184 non-null    datetime64[ns]
 1   Open       184 non-null    float64
 2   High       184 non-null    float64
 3   Low        184 non-null    float64
 4   Close      184 non-null    float64
 5   Adj Close  184 non-null    float64
 6   Volume     184 non-null    int64
dtypes: datetime64[ns](1), float64(5), int64(1)
memory usage: 10.2 KB
None

In [ ]:
print(df.describe())

                                Date        Open        High         Low  \
count                            184  184.000000  184.000000  184.000000
mean   2016-06-30 11:28:41.739130368  127.040245  129.918098  124.340381
min              2014-09-29 00:00:00   92.389999   93.769997   89.470001
25%              2015-08-15 06:00:00  108.882499  112.362499  106.152502
50%              2016-06-30 12:00:00  118.895000  120.865002  116.870003
75%              2017-05-16 18:00:00  144.935005  147.695000  143.227493
max              2018-03-29 00:00:00  180.289993  183.500000  177.619995
std                              NaN   24.314449   24.577906   24.176736

            Close   Adj Close        Volume
count  184.000000  184.000000  1.840000e+02
mean   127.352663  123.838032  1.910168e+08
min     90.519997   87.796822  3.839850e+07
25%    109.204998  105.301765  1.273706e+08
50%    119.190002  114.999730  1.744112e+08
75%    144.704994  143.039467  2.207755e+08
max    179.979996  179.979996  5.003630e+08
std     24.356534   25.655569  8.160281e+07

In [ ]:
print(df.isnull().sum())

Date         0
Open         0
High         0
Low          0
Close        0
Adj Close    0
Volume       0
dtype: int64

In [ ]:
df = df.dropna()

In [ ]:
df = df.drop_duplicates()
df

,Date,Open,High,Low,Close,Adj Close,Volume
0,2014-09-29,100.589996,100.690002,98.040001,99.620003,93.514290,142718700
1,2014-10-06,99.949997,102.379997,98.309998,100.730003,94.556244,280258200
2,2014-10-13,101.330002,101.779999,95.180000,97.669998,91.683792,358539800
3,2014-10-20,98.320000,105.489998,98.220001,105.220001,98.771042,358532900
4,2014-10-27,104.849998,108.040001,104.699997,108.000000,101.380676,220230600
...,...,...,...,...,...,...,...
179,2018-03-05,175.210007,180.000000,174.270004,179.979996,179.979996,139852700
180,2018-03-12,180.289993,183.500000,177.619995,178.020004,178.020004,155417500
181,2018-03-19,177.320007,177.470001,164.940002,164.940002,164.940002,172670700
182,2018-03-26,168.070007,175.149994,165.190002,167.779999,167.779999,157898400
183,2018-03-29,167.804993,171.750000,166.899994,167.779999,167.779999,38398505

In [ ]:
df = df.sort_values("Date")

In [ ]:
df["Daily_Delta"] = df["Close"] - df["Open"]

In [ ]:
df["Daily_Return"] = (
    (df["Close"] - df["Open"]) / df["Open"]
) * 100

In [ ]:
print(df[
    ["Date", "Open", "Close", "Daily_Delta", "Daily_Return"]
].head())

        Date        Open       Close  Daily_Delta  Daily_Return
0 2014-09-29  100.589996   99.620003    -0.969993     -0.964304
1 2014-10-06   99.949997  100.730003     0.780006      0.780396
2 2014-10-13  101.330002   97.669998    -3.660004     -3.611965
3 2014-10-20   98.320000  105.220001     6.900001      7.017902
4 2014-10-27  104.849998  108.000000     3.150002      3.004294

In [ ]:
average = df[['Close', 'Open']].mean()
maximum = df[['Close', 'Open']].max()
minimum = df[['Close', 'Open']].min()

print("Average:", average)
print("Maximum:", maximum)
print("Minimum:", minimum)

Average: Close    127.352663
Open     127.040245
dtype: float64
Maximum: Close    179.979996
Open     180.289993
dtype: float64
Minimum: Close    90.519997
Open     92.389999
dtype: float64

In [ ]:
threshold = 2 * average
print(threshold)

Close    254.705326
Open     254.080489
dtype: float64

In [ ]:
anomalous_days = df[df["Volume"] > volume_threshold]

In [ ]:
print("\nAnomalous Trading Days:")
print(anomalous_days[ ["Date","Open","Close","Daily_Delta","Daily_Return","Volume"] ])

Anomalous Trading Days:
          Date        Open       Close  Daily_Delta  Daily_Return     Volume
17  2015-01-26  113.739998  117.160004     3.420006      3.006863  465842700
30  2015-04-27  132.309998  128.949997    -3.360001     -2.539491  420972300
44  2015-08-03  121.500000  115.519997    -5.980003     -4.921813  385000600
47  2015-08-24   94.870003  113.290001    18.419998     19.416040  500363000
102 2016-09-12  102.650002  114.919998    12.269996     11.953235  388228200

In [ ]:
mean_return = df["Daily_Return"].mean()
variance_return = df["Daily_Return"].var()
std_return = df["Daily_Return"].std()

print("Mean Return:", mean_return)
print("Variance:", variance_return)
print("Standard Deviation:", std_return)

Mean Return: 0.30716273695058094
Variance: 12.289199177244166
Standard Deviation: 3.5055954098047546

In [ ]:
average_volume = df['Volume'].mean()
minimum_volume = df['Volume'].min()
maximum_volume = df['Volume'].max()

print(f"Average Trading Volume: {average_volume:,.2f}")
print(f"Minimum Trading Volume: {minimum_volume:,.2f}")
print(f"Maximum Trading Volume: {maximum_volume:,.2f}")

Average Trading Volume: 191,016,776.11
Minimum Trading Volume: 38,398,505.00
Maximum Trading Volume: 500,363,000.00

In [ ]:
top_10_volume_days = df.sort_values(by='Volume', ascending=False).head(10)
display(top_10_volume_days[['Date', 'Volume', 'Open', 'Close']])

          Date     Volume        Open       Close
47  2015-08-24  500363000   94.870003  113.290001
17  2015-01-26  465842700  113.739998  117.160004
30  2015-04-27  420972300  132.309998  128.949997
102 2016-09-12  388228200  102.650002  114.919998
44  2015-08-03  385000600  121.500000  115.519997
69  2016-01-25  380336500  101.519997   97.339996
21  2015-02-23  368216200  130.020004  128.460007
2   2014-10-13  358539800  101.330002   97.669998
3   2014-10-20  358532900   98.320000  105.220001
82  2016-04-25  349424100  105.000000   93.739998